#! /bin/bash

#SBATCH -p RC
#SBATCH -J Ce_model
#SBATCH -o Ce_npne_Results%j.out
#SBATCH -t 0-00:30

#SBATCH -N 1
#SBATCH -n 20

module list
echo "$(hostname), reporting for duty."

srun echo "Let's run the model!"
srun python Ce.py
srun echo "Simulation complete."
